apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-headless
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432