nodeName: "desktop-msi-z490"

postgres:
  existingSecret: postgres-secret-prod
  persistence:
    size: 2Gi
    volumeName: "prod-postgres-pv"
  
backend:
  existingSecret: backend-secret-prod
  image:
    tag: "prod-build"
  springProfile: prod
  persistence:
    size: 5Gi
    volumeName: "prod-media-pv"

frontend:
  image:
    tag: "prod-build"
  env:
    VITE_API_BASE_URL: "http://api.familyheritage.192.168.100.144.nip.io"

ingress:
  enabled: true
  host: "familyheritage.192.168.100.144.nip.io"
  apiHost: "api.familyheritage.192.168.100.144.nip.io"