nodeName: "desktop-msi-z490"

postgres:
  existingSecret: postgres-secret-staging
  persistence:
    size: 2Gi
    volumeName: "staging-postgres-pv"
  
backend:
  existingSecret: backend-secret-staging
  image:
    tag: "staging-build"
  springProfile: staging
  persistence:
    size: 5Gi
    volumeName: "staging-media-pv"

frontend:
  image:
    tag: "staging-build"
  env:
    VITE_API_BASE_URL: "http://api.staging.192.168.100.144.nip.io"

ingress:
  enabled: true
  host: "staging.192.168.100.144.nip.io"
  apiHost: "api.staging.192.168.100.144.nip.io"