nodeName: "desktop-msi-z490"
postgres:
  existingSecret: postgres-secret-dev
  persistence:
    size: 2Gi
    volumeName: "dev-postgres-pv"
backend:
  existingSecret: backend-secret-dev
  image:
    tag: ""
  imagePullPolicy: Always
  springProfile: dev
  persistence:
    size: 5Gi
    volumeName: "dev-media-pv"
frontend:
  image:
    tag: ""
  imagePullPolicy: Always
  env:
    VITE_API_BASE_URL: "http://api.dev.192.168.100.144.nip.io"
ingress:
  enabled: true
  host: "dev.192.168.100.144.nip.io"
  apiHost: "api.dev.192.168.100.144.nip.io"
