apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  {{- if .Values.backend.persistence.volumeName }}
  volumeName: {{ .Values.backend.persistence.volumeName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
  storageClassName: manual